[tool.bumpversion]
current_version = "0.8.1"
commit = true
tag = true
tag_name = "{new_version}"

[[tool.bumpversion.files]]
filename = "docs/conf.py"
parse = 'release\s*=\s*"(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)'

[[tool.bumpversion.files]]
filename = "formasaurus/__init__.py"
